### ISSUE TITLE
Reconnecting gives an error : Cannot join with an existing log

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#12]
I've been testing this out a bit, am really excited about it. But I'm having an issue, that whenever a client disconnects, or I cancel the process then try to reconnect to the master node, it gives me the following error:
```
[03/01/15 14:56:14] [INFO] Initializing Raft Server: node.3
[03/01/15 14:56:14] [INFO] Loading latest snapshot, if any, from disk
[03/01/15 14:56:14] [INFO] Attempting to join leader at localhost:4001
[03/01/15 14:56:14] [EROR] Cannot join with an existing log
[03/01/15 14:56:14] [EROR] Cannot join with an existing log
```

Does this mean that rqlite has no ability to reconnect to the master, without starting from scratch? What if the .sqlite DB has gigabytes worth of data. Obviously you wouldn't want to have to resync the whole thing just because of a disconnection.

My use case for this consists of many clients connecting and dropping out at will.

Thanks in advance.

**Comment by otoolep** [comment]
I think you're passing `-join` again, when restarting the process. Don't do that -- simply start the process without the `-join` command, but be sure to still pass the "node" directory path. `-join` is only for one-time use.

If this addresses the issue, let me know. I can then clarify the documentation.

**Comment by tchoulihan** [comment]
Hrm, if I leave off the '-join **master_peer**, it seems to load up fine, but I'm not sure if it attached to the master or is running on its own node now.

The raft admin query(`curl localhost:4001/raft?pretty`) seems to show the peers connected, even if they are actually disconnected.

``` 
~/rqlite$ bin/rqlite localhost:4001 -p 4002 node.2
[03/01/15 15:22:58] [INFO] Redirectoring logging to stdout
[03/01/15 15:22:58] [INFO] Raft random seed initialized
[03/01/15 15:22:58] [INFO] Raft commands registered
[03/01/15 15:22:58] [INFO] Initializing Raft Server: localhost:4001
[03/01/15 15:22:58] [INFO] Loading latest snapshot, if any, from disk
[03/01/15 15:22:58] [INFO] Recovered from log
[03/01/15 15:22:58] [INFO] Initializing HTTP server
[03/01/15 15:22:58] [INFO] Listening at http://localhost:4001
[03/01/15 15:22:58] [EROR] listen tcp :4001: bind: address already in use
```

**Comment by otoolep** [comment]
Pass nothing on restart except the path and the port. For example, if the node was restarted like so:

`rqlite -join localhost:4001 -p 4003 ~/node.3`

it should always be *restarted* like so:

`rqlite -p 4003  ~/node.3`

Joining is a special case, only executed once. Once joined, a node gets all else it needs on a restart from the data in its node directory.

As for the `raft` endpoint, that returns the nodes that are members of in the cluster, not which are actively up.

**Comment by tchoulihan** [comment]
Cool, thanks Philip, that makes things easy. Would it be possible to a 'isActive' or 'isConnected' field to that admin query? This would be really useful to me, rather than having to query individual nodes and see if they fail.

Something like:
```
{
    "peers": {
        "2456e8c": {
            "name": "2456e8c",
            "connectionString": "http://localhost:4002",
            "isConnected" : "false" 
       ...
```

BTW I'm pretty excited about the results so far. Replication seems instant, on the localhost at least.

**Comment by otoolep** [comment]
Sure definitely makes sense to me. I have opened a ticket:

https://github.com/otoolep/rqlite/issues/13

I am also going to update the README so restart is clarified.

**Comment by tchoulihan** [comment]
Thanks a ton man.
