### ISSUE TITLE
Changing leader after initialization? IE, what if the leader disconnects?

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#15]
Hey Philip, I have a question regarding leader disconnects. My use case is not just a replicated data, but a decentralized data store. 

So Lets say I have 10 nodes, the first one being a leader. For some reason or another, the leader drops out(network reasons or other). But the network has to stay functional. Because of this, lets say I want to elect a new leader, IE node #2 . 

There are several ways to handle. Here's a list of solutions that I have in order of preference.

* Option 1) If the leader goes down, then change the leader to the 2nd peer in the list. All nodes have the list of peers anyway, and can (once you handle issue #13 ), see which ones are active. 
  * Users could then either manually change their curl XPOST statements to point to a new leader, or what would be a lot better, is if XPOST statements went to their own local node and redirected to the current leader. They already knows the leader location anyway, so I don't see why this wouldn't be doable. Currently if I try this, I get the following error: `"error":"raft.Server: Not current leader"` 
* Option 2) Notice that the leader requests are failing, and have the other nodes do a -join to the second node, which they can get from their own peer lists. This is really not optimal, because right now, a -join requires a completely clear directory, so the DB would need to be resynced. 

BTW, here's what happens if I try to simulate the above conditions with your 3 node example:
1) Start up 3 nodes
2) Node #1 goes down, nodes 2 and 3 still show #1 being the leader.(Their /raft endpoints)
3) Try to make node 3 point to a new leader node 2, unfortunately have to clear the directory and do a whole DB resync because of the -join command. Connect to node 2.

Here's the raft endpoint outputs of node 2 and 3. Some things to notice are that node 2 does correctly say that its the leader, and the info appears to be correct. IMO though, its not really an acceptable solution because it requires all the other nodes to delete their directories.
EDIT: oddly node 3 shows itself to be its own peer in this case, and has two names. I'm not sure why.

```
~/rqlite$ curl localhost:4002/raft?pretty
{
    "leader": "26403fc",
    "name": "26403fc",
    "peers": {
        "1669380": {
            "name": "1669380",
            "connectionString": "http://localhost:4003"
        },
        "4630386": {
            "name": "4630386",
            "connectionString": "http://localhost:4001"
        }
    },
    "state": "leader"
}
curl localhost:4003/raft?pretty
{
    "leader": "26403fc",
    "name": "6ff833e",
    "peers": {
        "1669380": {
            "name": "1669380",
            "connectionString": "http://localhost:4003"
        },
        "26403fc": {
            "name": "26403fc",
            "connectionString": "http://localhost:4002"
        },
        "4630386": {
            "name": "4630386",
            "connectionString": "http://localhost:4001"
        }
    },
    "state": "follower"
}
```

**Comment by otoolep** [comment]
When you say "change the leader" you mean the cluster elects a new leader, right? I just want to be sure.

If I understand this issue, it's basically the same as wanting redirects, right? If we had that, this wouldn't be an issue, correct?

**Comment by otoolep** [comment]
The cluster now has basic leader redirection, though I have not performed extensive testing. I just checked that `curl -L ....` is redirected to the leader node. Let me know how it goes.

**Comment by tchoulihan** [comment]
> When you say "change the leader" you mean the cluster elects a new leader, right? I just want to be sure.

Yep that's correct. 

I just did some testing and it looks like things are okay! I set up the 3 node example, took down node.1(the first leader). And the outputs look good. 

Node 3 was arbitarily chosen as the new leader when I did this:
```
curl localhost:4002/raft?pretty
{
    "leader": "1d4e168",
    "name": "7d2502e",
    "peers": {
        "1b2bcd5": {
            "name": "1b2bcd5",
            "connectionString": "http://localhost:4001"
        },
        "1d4e168": {
            "name": "1d4e168",
            "connectionString": "http://localhost:4003"
        }
    },
    "state": "follower"
}
 curl localhost:4003/raft?pretty
{
    "leader": "1d4e168",
    "name": "1d4e168",
    "peers": {
        "1b2bcd5": {
            "name": "1b2bcd5",
            "connectionString": "http://localhost:4001"
        },
        "7d2502e": {
            "name": "7d2502e",
            "connectionString": "http://localhost:4002"
        }
    },
    "state": "leader"
```

One minor issue though, it doesn't look like the `-L` parameter works with the raft endpoint. Node 3 is the leader in my case, but the raft endpoint for node 2 still shows node 2's data. 

```
curl -L localhost:4002/raft?pretty
{
    "leader": "1d4e168",
    "name": "7d2502e",
    "peers": {
        "1b2bcd5": {
            "name": "1b2bcd5",
            "connectionString": "http://localhost:4001"
        },
        "1d4e168": {
            "name": "1d4e168",
            "connectionString": "http://localhost:4003"
        }
    },
    "state": "follower"
```

IMO, this doesn't really matter because the same node's raft endpoint tells you enough data anyway. 

Looking back over my first post in this thread, I'm seeing that I made an error and that rqlite is actually doing the leader reselection perfectly. 

You can close this out if you like. Remember to add the -L page to your Readme. Thanks a ton man, this stuff is pretty exciting for me.

**Comment by otoolep** [comment]
Let me look into the issue you mentioned above, but that is a good idea about adding `-L` to the README.

**Comment by otoolep** [comment]
Ok, yeah, I only put leader redirection in place for the write endpoint. If you want stats, diags, etc, you need to go out and hit each node individually. Let me know if this is an issue.
