### ISSUE TITLE
Automatically redirect XPOSTS to the leader

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#16]
As I stated in issue #15 , it would be extremely helpful if I could send my XPOSTS/inserts and updates to my own node, which is always available. Since it knows the leader anyway, it should be able redirect these. So in your 3 node example, I'd run the line `curl -XPOST localhost:4003/db -d 'yada yada'`, and it could redirect the XPOST to the current leader as shown in `curl localhost:4003/raft?pretty`

Right now, if I try an XPOST on my own node, I get the error:
`"error":"raft.Server: Not current leader"`

**Comment by otoolep** [comment]
This is actually a detail within the Raft implementation, so is not a trivial fix to my code. I would need to "vendor" the code to fix this. Not ruling it out, but it may not happen soon.

**Comment by otoolep** [comment]
Fixed by https://github.com/otoolep/rqlite/commit/106296515fd393f1091130245f4b386c4f93fb78

**Comment by tchoulihan** [comment]
Thanks @otoolep .  I'm not sure how go's builds/deployment works, is this commit included now in `go get github.com/otoolep/rqlite` ? Either way, I'll test this out.

**Comment by tchoulihan** [comment]
Thanks, just tested this out and it works. Just for reference, I'd like to add that the curl -L is what does this. So an example command is:
`curl -XPOST localhost:4002/db?pretty -L -d 'INSERT INTO foo(name) VALUES("fionaderp")'`
