### ISSUE TITLE
-join command to a follower node? Maybe redirect/forward to the leader.

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#17]
I've been testing what happens when a node uses the -join command on another node that is **not** the leader of his network. IE, what happens when you run -join on a node that is currently a follower?

Here's how I'm going about it:

* Create a two-node network. Node.1(Leader) and Node.2(Follower)
* Create a Node.3, and use the -join command to connect to Node.2

When I do this, I get some strange results.
* Node 1 shows only Node 2 as its peer follower.
* Node 2 shows only Node 1 as the leader, and leaves out node 3
* Node 3 shows no peers at all.

My preferred solution to this, is that if the -join command is trying to connect to a follower, then to automatically redirect/forward that join command to that network's leader. Other solutions might be to throw an error(it didn't),with the output address of that node's leader. 

Here's the output of of the raft endpoints:
```
curl localhost:4001/raft?pretty 
{
    "leader": "38ce511",
    "name": "38ce511",
    "peers": {
        "6731b4c": {
            "name": "6731b4c",
            "connectionString": "http://localhost:4002"
        }
    },
    "state": "leader"
}
curl localhost:4002/raft?pretty 
{
    "leader": "38ce511",
    "name": "6731b4c",
    "peers": {
        "38ce511": {
            "name": "38ce511",
            "connectionString": "http://localhost:4001"
        }
    },
    "state": "follower"
}
curl localhost:4003/raft?pretty 
{
    "leader": "",
    "name": "7519049",
    "peers": {},
    "state": "follower"
```

**Comment by otoolep** [comment]
Change https://github.com/otoolep/rqlite/commit/45fef88a7a16f299470e733a09d2e67183316cba means that if an attempt it made to join a node that is not the leader, the request will be redirected to the leader, and joining node will follow that redirect.

This should address your issue.

**Comment by tchoulihan** [comment]
Just tested this out, and everything looks good. It gives these lines which are helpful:
```
[03/05/15 11:01:31] [INFO] Attempting to join leader at localhost:5002
[03/05/15 11:01:31] [INFO] Redirecting to leader at localhost:5001
```

Thanks a ton sir.
