### ISSUE TITLE
Good for multiple clients/server sync?

### ISSUE THREAD

**Issue by mamcx** [otoolep/rqlite#18]
I have hunting for a way to sync safely sqlite databases. However I need to do multiple iOS - Server.

I understand that I need to build a raft client, so the question is if this approach (ie: using raft) could work for sync ios-server...

**Comment by otoolep** [comment]
Using Raft to sync databases wouldn't really work because it assumes that the nodes are generally in communication, and a quorum can be established so that changes can be replicated across a cluster. That doesn't apply to devices at the edge of network like iPhones.

**Comment by otoolep** [comment]
Thanks for your question though @mamcx .
