### ISSUE TITLE
Deprecate code.google.com/p/log4go

### ISSUE THREAD

**Issue by fern4lvarez** [otoolep/rqlite#21]
https://code.google.com is shutting down. Also, https://code.google.com/p/log4go has been unmaintained for [more than three years](https://code.google.com/p/log4go/source/list). Furthermore, Go's standard library is awesome and the community is embracing it, and using third-party libraries only when mandatory (see [Three falacies of dependencies](https://www.youtube.com/watch?v=yi5A3cK1LNA)).

The options here:
- Let `log4go` rest in peace and use `log` package instead.
- Grab one of the `log4go` clones on Github (e.g https://github.com/alecthomas/log4go) and use it, so only the import path must be changed.
- Find another high-level log implementation and replace it (e.g. https://github.com/golang/glog)

Thoughts?

**Comment by otoolep** [comment]
Completely agree. We should pull log4go and use the standard log package that comes with Go. I used log4go, as I was following patterns in some other projects, but now know better.

http://blog.gopheracademy.com/advent-2014/case-against-3pl/
