### ISSUE TITLE
Allow leader redirection to be disabled

### ISSUE THREAD

**Issue by otoolep** [otoolep/rqlite#28]
Leader re-direction was recently enabled. It should be possible to disable this via a command line-switch.

**Comment by fern4lvarez** [comment]
Can you maybe link to the commit or code snippet where this was enabled? Thanks!

**Comment by otoolep** [comment]
https://github.com/otoolep/rqlite/commit/45fef88a7a16f299470e733a09d2e67183316cba

It's only on join. Line 318 needs to executed conditionally.

**Comment by otoolep** [comment]
No longer valid.
