### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bluesun08** [otoolep/rqlite#30]
Hi,
when i execute "go get github.com/otoolep/rqlite" i get the following error:

src/code.google.com/p/goprotobuf/proto/text.go:39:2: no Go source files in /usr/lib/go/src/pkg/encoding

Whats the problem?

**Comment by otoolep** [comment]
Can you please show the entire sequence, including setting your GOPATH. 

------------------------------------
http://www.philipotoole.com

**Comment by otoolep** [comment]
Have heard no more -- closing.
