### ISSUE TITLE
Peers should be an array

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#31]
I'm starting to do some json templating of a network status page of rqlite, and I'm noticing something that doesn't seem right. The 'raft' endpoint that returns json has a peers element, that should be a json array, not a map like it currently is.

Right now its:
```
{
    "peers": {
        "2456e8c": {
            "name": "2456e8c",
            "connectionString": "http://localhost:4002",
            "isConnected" : "false" 
       ...
```

And it should be:
```
{
    "peers": [{
            "name": "2456e8c",
            "connectionString": "http://localhost:4002",
            "isConnected" : "false" 
       ...
```

This way I could iterate over the peers array correctly using mustache/handlebars.

**Comment by otoolep** [comment]
Well, it is legal JSON. :-)

Yeah, it does look a bit weird, I'll grant you that. It's what comes back from the go-raft module actually, but I don't mind changing.

**Comment by otoolep** [comment]
```
$ curl localhost:4001/raft?pretty
{
    "leader": "14af844",
    "name": "14af844",
    "peers": [
        {
            "name": "5da4e34",
            "connectionString": "http://localhost:4002"
        }
    ],
    "state": "leader"
}
```

**Comment by otoolep** [comment]
Fixed by https://github.com/otoolep/rqlite/commit/7a4c98f383b0721b0f6fc7c7d2f501352619446a

**Comment by tchoulihan** [comment]
Damn you're fast! Thanks again good sir.
