### ISSUE TITLE
Statistics endpoint, dots in variable names

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#32]
In most templating engines, dots are illegal to use for variable names, since they traverse sub-objects. 

So as a result, I'm unable to access variables like execute.Received
```
  "statistics" : {
    "server" : {
      "execute.Received" : {
        "count" : 2
      },
```

Could these dots be changed to a different delimiter? Maybe underscores, or just make another embedded object.

**Comment by otoolep** [comment]
Thanks @tchoulihan -- that is eminently sensible. I changed it.

https://github.com/otoolep/rqlite/commit/e51c9ef704635477203b6e29e8862959ca519dd0

**Comment by tchoulihan** [comment]
Thanks a ton man.
