### ISSUE TITLE
How to do a restore after updating to a new version of rqlite?

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#34]
Hey @otoolep , whats the best way to do a restore?

I needed to update to a new version of rqlite, so I saved the db.sqlite file. 

Then I reinstalled rqlite and replaced the db.sqlite file, but it doesn't appear to work correctly.

Will copying the whole data/db directory work?

Thanks.

**Comment by otoolep** [comment]
Yeah, restoring just the database file will not be sufficient. I haven't deeply tested restoring the entire data directory, but I believe that should work.

**Comment by otoolep** [comment]
The IP addresses of the nodes in the cluster are contained within that directory. If you expect to be able to move the data directory to a new host with a new hostname, that won't work as far as I know. You could try re-writing the files in the data directory that store the hostname if you needed to -- you'd need to do this on every node.

**Comment by tchoulihan** [comment]
Gotcha, next time I update rqlite I'll test it out.
