### ISSUE TITLE
Node getting stalled on snapshotting / empty connection strings

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#43]
Sometimes I'll have a node disconnect, and just try to restart it in the correct way, but its raft log will say that its snapshotting:
```
{
    "leader": "38567ec",
    "name": "57e97c8",
    "peers": [
        {
            "name": "7da05d3",
            "connectionString": "http://104.236.44.89:4570"
        },
        {
            "name": "38567ec",
            "connectionString": ""
        }
    ],
    "state": "snapshotting"
```

Once its like this it can never rejoin again.

**Comment by tchoulihan** [comment]
Also, as in the example above, sometimes the connection string for certain connections will be empty and it will mess things up.

I've noticed the leader will show the correct connection, but the joiner might show it as empty.

**Comment by tchoulihan** [comment]
Hey @otoolep 

So I've launched my application, here's the admin page. It ran for a day, with 6 peers, and now is stuck in a glitch where all the nodes keep switching back between candidates and followers with no leader. If you refresh the page you'll see it. I'm guessing this has to do with some major errors in goraft.

http://107.170.137.106:4568/network

Someone suggested to me that I should be using this here, since goraft is unmaintained.
https://github.com/coreos/etcd/tree/master/raft

That should replicate all the functions, but its also supported.
Is there any chance that rqlite could switch to this? I'm having a lot of reliability issues.

**Comment by otoolep** [comment]
Thanks @tchoulihan -- at this time, it's unlikely I'll be swapping out the Raft implementation within rqlite anytime soon. Doing so would not be trivial so would take a little while.

**Comment by otoolep** [comment]
To be clear, I do hope to fix these issues at some point, but I can't give you a timeframe, since these issues may not be trivial.

**Comment by tchoulihan** [comment]
@otoolep no problem. These reliability issues are the current bottleneck in my project, enough that I want to start to work some of them out and do some pull requests. 

Which is the main class I should be looking at that does the leader selection, maybe main.go or server.go?

**Comment by otoolep** [comment]
Leader "election", which I presume if what you mean, is not performed by code I wrote. It's performed by https://github.com/goraft/raft. That said, once you clone the entire repo, and build it, you'll have the go-raft source also locally, which you can edit and try out fixes.

**Comment by tchoulihan** [comment]
Yep, and the leader election is completely broken. Right now, after running for a day, they're all stalled as candidates, permanently.

Could you point me to which .go file of yours calls goraft, or initiates the leader election?

**Comment by otoolep** [comment]
Nothing in rqlite does any of that.

The way it works is that rqlite registers commands with the go-raft module (write, read, and shapshot), and then let's go-raft do its thing. go-raft then decides when those commands should be called in rqlite, when a new leader should be elected etc etc. It might help if you study the reference implementation here:

https://github.com/goraft/raftd

**Comment by otoolep** [comment]
I've swapped out the Raft implementation, so this is moot.
