### ISSUE TITLE
Best way to implement a whitelist of nodes for a cluster(IE only let certain IPs join the rqlite cluster)?

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#45]
Hey @otoolep , I'm not sure if this is an issue or not, but I'd like your expertise on the best way to implement a whitelist of nodes.

So lets say I only want **certain** IP addresses or connection strings to be able to join the network, for security reasons. 

One solution I thought about is to just use an abstraction layer in my own project, to pass a parameter like:
`-whitelist IP_ADDR_1 IP_ADDR_2 ` , etc. 

I can do this in my own project as an abstraction layer, but let me know if this is something you'd be interested in building, and I won't do this.

**Comment by otoolep** [comment]
Hello - no, I would consider network security outside the scope of rqlite. It is very unlikey I would implement something like this. 

There are lots of other options. Firewalls, iptabled, EC2 security groups, etc.

**Comment by tchoulihan** [comment]
@otoolep No problem, very understandable.
