### ISSUE TITLE
can't build rqlite; goprotobuf error

### ISSUE THREAD

**Issue by tchoulihan** [otoolep/rqlite#46]
I'm getting this error when I run `go get github.com/otoolep/rqlite`:
```
package github.com/otoolep/rqlite
	imports github.com/goraft/raft
	imports code.google.com/p/gogoprotobuf/proto
	imports code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path
```

Since google code is going away, I'm guessing the correct repo is here,
https://github.com/golang/protobuf

**Comment by otoolep** [comment]
If that change works, do you want to generate a PR?

**Comment by tchoulihan** [comment]
Sure, let me test it out

**Comment by tchoulihan** [comment]
So I'm finding rqlite only uses that protobuf dependency indirectly through goraft, which is deprecated/unmaintained. A short term fix then would be to fork goraft, update that dependency, until you eventually move to that new goraft you referenced earlier. I'll start on this now.

**Comment by tchoulihan** [comment]
I just messed with this a bunch, and still can't figure it out. I forked goraft, replaced all references of either goprotobuf or gogoprotobuf to the new github one using the following find and replace command:
```
find . -type f -exec sed -i 's/code.google.com\/p\/goprotobuf/github.com\/golang\/protobuf/g' {} +
find . -type f -exec sed -i 's/code.google.com\/p\/gogoprotobuf/github.com\/golang\/protobuf/g' {} +
```

I don't really know much about building or testing go projects, but running `go test`, or `go install` just tell me that it can't find that new package, even after I've set the GOPATH to the goraft directory, and ran `go get github.com/golang/protobuf/proto`. 

Either this dependency is too complicated for me to fix, or I'm missing something.

**Comment by tchoulihan** [comment]
@otoolep Just to let you know, rqlite is still uninstallable because of this missing dependency, and its holding up my dev work.

**Comment by otoolep** [comment]
Fixed by https://github.com/otoolep/rqlite/commit/7f4105432fc37eca7a08da91f2ef6b874f660fab

**Comment by tchoulihan** [comment]
Wow I didn't realize it was as simple as using that embedded folder, thanks a bunch sir.

**Comment by otoolep** [comment]
It wasn't actually, I also had to update my fork of raft. Not a huge deal.

**Comment by tchoulihan** [comment]
Ah gotcha, wish I had more expertise with go to save you the work, but thanks again anyway.
