### ISSUE TITLE
Injections and Authentication

### ISSUE THREAD

**Issue by Apercu** [otoolep/rqlite#47]
Hi,

I'm wondering how to sanitize queries to be safe from SQL injections. Indeed since there is only the HTTP API, we can't prepare so any query might not be safe. Is there a recommended pattern to apply?

Also, since there is no users or authentication process before running queries, should a rqlite cluster be run behind a proxy, or did a miss something?

Thanks for your work!

**Comment by otoolep** [comment]
@Apercu -- sanitizing the queries is up to you. It's no different than if you were issuing SQLite queries directly. The best way to handle this is put something (your own little program, for example) in-front of rqlite, that sanitizes each query before passing it on. The same approach could be used to enforce authentication. 

This is interesting functionality, and building it into rqlite would be a good idea though.

**Comment by zmedico** [comment]
> The same approach could be used to enforce authentication.

That may work for the HTTP interface, but the RAFT connections will require authentication support directly in rqlited. Using the [consul security model](https://www.consul.io/docs/internals/security.html) as an example, we might use symmetric key encryption for RAFT connections, and TLS for the HTTP interface.

**Comment by zmedico** [comment]
The raft connections can be secured via a mesh vpn such as [meshbird](https://github.com/meshbird/meshbird).
