### ISSUE TITLE
Decoupling SQL Syntax in Post / Get APIs

### ISSUE THREAD

**Issue by heckdevice** [otoolep/rqlite#48]
Do you have any plans of making the SQL agnostic ReST APIs and do a thin API resource transformation into SQL Call within the server to decouple the clients from SQL Syntax?

For trivial data modification / retrieval it will ease the Client side query generation and give a more ReSTFul feel to the API Layer.

For post the table name can go as a rest url and data in form of json array payload there by merging the single insert & batch insert into a single rest endpoint interaction.

Also for retrieval the Column key val can be query params and pk be path params

**Comment by otoolep** [comment]
Thanks for your question @heckdevice -- no I don't have any plans for that, but it would be easy enough to code. PRs welcome. :-)

It would need to run as a second API server, or a switch the command line to invoke it, as some people rely on the current API.

**Comment by paul-hammant** [comment]
It'd be great if there were a --rest-port option, IMO.

**Comment by otoolep** [comment]
@paul-hammant -- what do you mean by "--rest-port"? You mean if I implemented this feature, I should be reachable at a different port than the HTTP service?

**Comment by paul-hammant** [comment]
My bad, I understood that there wasn't a REST (GET/PUT) capable API already.
