### ISSUE TITLE
return 'SELECT last_insert_rowid()' result executed just before transaction commit

### ISSUE THREAD

**Issue by zmedico** [otoolep/rqlite#50]
When inserting a row into a table with an automatically generated primary key, it can be very useful to return the newly allocated primary key value which is returned by `SELECT last_insert_rowid()`, so it can be inserted as a foreign key in another table. Unless the `SELECT last_insert_rowid()` statement is executed in the same transaction as the `INSERT` statement, it is needlessly complex to determine the value of the newly allocated primary key.

I have a python driver for rqlite, which I will release soon, and I would like to use this feature to implement the Cursor.lastrowid attribute.

**Comment by otoolep** [comment]
Thanks, let me see what I can do. I am re-working some rqlite (though the API should remain the same, I plan to just rework the distributed consensus part).

**Comment by otoolep** [comment]
What do you see if you issue the query today? I have not tested it.

**Comment by zmedico** [comment]
> What do you see if you issue the query today? I have not tested it.

The last_insert_rowid() function works fine as it is, for example:
```
$ curl -L -XPOST 'localhost:4001/db?pretty&explain' -d '
CREATE TABLE foo (id integer not null primary key, name text);
INSERT INTO foo(name) VALUES("fiona");
SELECT last_insert_rowid() as rowid;
'
{
    "time": "1.254978ms",
    "failures": []
}
```
Since the above doesn't return the row id, it has to be retrieved as a separate transaction:
```
$ curl -L -G 'localhost:4001/db?pretty&explain' --data-urlencode 'q=SELECT last_insert_rowid() as rowid'
{
    "time": "282.159µs",
    "failures": [],
    "rows": [
        {
            "rowid": "1"
        }
    ]
}
```

**Comment by otoolep** [comment]
OK, I believe I know why this is -- it's because rqlite isn't built to support statements that mutate the database and return results, in the same POST body.

I should be able to fix that, I've never been too happy about it, and know better now.

**Comment by otoolep** [comment]
Let me try to fix it as part of the work I am doing in this branch: https://github.com/otoolep/rqlite/tree/hrqlite

**Comment by zmedico** [comment]
It's also useful to return number of rows affected by an `UPDATE` statement. This value can be queried using `SELECT changes() as changes`. If have tested this function with rqlite, and it also works:
```
$  curl -L -G 'localhost:4001/db?pretty&explain' --data-urlencode 'q=
SELECT changes() as changes, last_insert_rowid() as last_insert_rowid'
{
    "time": "225.588µs",
    "failures": [],
    "rows": [
        {
            "changes": "1",
            "last_insert_rowid": "1"
        }
    ]
}
```

I can use this to implement python's Cursor.rowcount attribute.

**Comment by otoolep** [comment]
This should now be fully supported on master. Please take a look @zmedico and let me know what you think.

**Comment by zmedico** [comment]
It works great, thank you!

**Comment by otoolep** [comment]
@zmedico -- are you planning to make your Python driver generally available? If so, I'd be interested in seeing in.

**Comment by otoolep** [comment]
I guess by "release soon" you do mean to make it available to general use.

**Comment by zmedico** [comment]
Yeah, I'm releasing it with MIT license:

https://github.com/zmedico/pyrqlite

Lots of things can be simplified thanks to the rqlite-2.0 API.

**Comment by zmedico** [comment]
I also made an sqlalchemy dialect that I used to test pyrqlite:

https://github.com/zmedico/sqlalchemy-rqlite

**Comment by otoolep** [comment]
Nice.

Depending on your seriousness, we should agree to lock down the API pretty soon. I think it's close, but I'd be interested in any feedback.

**Comment by zmedico** [comment]
I'm pretty happy with the 2.0 API as it currently is, but I think that ideally the URI would include a version component so that multiple versions can be supported simultaneously. Each version doesn't have to be supported forever. I'm not particularly invested in the 1.0 API, so I don't really care if it's dropped now (though it shouldn't be terribly difficult to continue supporting it).

What are your thoughts on adding a version component to the URI?

**Comment by otoolep** [comment]
I'm going to resist versioning the API for now, since the 1.0 API was badly done, and should never have existed in that form (after spending a couple of years building databases I know better now, you see). I think versioning might be overkill for my goals for rqlite.

As for the API, I've made some final changes. Check out the https://github.com/otoolep/rqlite/blob/master/README.md for full details.

**Comment by zmedico** [comment]
> As for the API, I've made some final changes. 

Looks good.

**Comment by zmedico** [comment]
Now [pyrqlite uses the rqlite 2.0 API] (https://github.com/zmedico/pyrqlite/commit/81e5815df374cdb366886123fd267b0ec6346c12).
