### ISSUE TITLE
Row columns ordered in JSON response differently from SQL statement, tricky to map to database APIs

### ISSUE THREAD

**Issue by zmedico** [otoolep/rqlite#51]
Many database APIs return row objects which are expected to have the columns in a particular order. Given the ordering of columns in rqlite JSON responses, it is tricky to map the columns into the order implied by the SELECT statement, since it involves parsing SQL. It would greatly simplify the implementation of database APIs if rqlite would return columns in the order implied by the SELECT statement.

**Comment by otoolep** [comment]
You're right @zmedico -- this is a fundamental problem with the responses of rqlite, that I didn't appreciate at the time I first created the program.

This definitely needs to be fixed, and I know how to do it, but will result in the output format being changed a bit. I'll try to fix this shortly.

**Comment by otoolep** [comment]
This is now fixed on master. Please check out the new API responses and tell me what you think @zmedico 

While master still needs more work, I am proposing the new API as final for 2.0. Let me know if you have any feedback.

**Comment by otoolep** [comment]
Check the README for all the latest details.

**Comment by zmedico** [comment]
Looks good, thanks! It's a big improvement, and maybe https://github.com/otoolep/rqlite/issues/52 isn't really essential, so I'm happy the new API as is.
