### ISSUE TITLE
Descriptions of column data types for query results in JSON response would be useful

### ISSUE THREAD

**Issue by zmedico** [otoolep/rqlite#52]
In order for a database API to map query results to specific types other than string, such as DATETIME, it would be useful to include the data types in the JSON response. Without this information, the database API implementation has to do a separate `PRAGMA table_info` query, and then parse the SQL statement to determine how those types map to result columns. It would greatly simplify database API implementations if the JSON response described the result column types.

**Comment by otoolep** [comment]
Not committing to fixing this for v2.0, but might get to it.

**Comment by zmedico** [comment]
The relevant info is stored in the sqlite3.SQLiteRows.decltype field (which is currently inaccessible outside the sqlite3 package).

**Comment by zmedico** [comment]
I have [a branch](https://github.com/zmedico/rqlite/tree/decltype) containing a patch that changes DB.Query to bypass sql.DB, allowing for access to SQLiteRows instances. Now sqlite3.SQLiteRows just needs a method to export the declaration types.

**Comment by zmedico** [comment]
Fixed by https://github.com/otoolep/rqlite/pull/71.
