### ISSUE TITLE
semicolon  in sql

### ISSUE THREAD

**Issue by millken** [otoolep/rqlite#53]
````
[root@cloud rqlite]# curl -L -XPOST localhost:4001/db?pretty -d '
>CREATE TABLE "server" ("id" INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,"servername" TEXT DEFAULT NULL,"setting" TEXT DEFAULT NULL,"created_at" INTEGER NOT NULL  DEFAULT CURRENT_TIMESTAMP,UNIQUE (servername));
>INSERT INTO "server" ("id", "servername", "setting")VALUES(2,"www.test1.com",'{"gzip": 1, "upstream": "server 127.0.0.1:81; server 127.0.0.1:82;"}');'
{
    "failures": [
        {
            "sql": "\nINSERT INTO \"server\" (\"id\", \"servername\", \"setting\")VALUES(2,\"www.test1.com\",{gzip:",
            "error": "unrecognized token: \"{\""
        }
    ]
curl: (6) Couldn't resolve host '1,'
curl: (6) Couldn't resolve host 'upstream:'
````

**Comment by zmedico** [comment]
It's a problem with your usage of quotes you shell, not a fault of rqlite. Here's an example of how to the the effect that you want (use echo to check correctness):
```
echo ', '\''{"gzip": 1, "upstream": "server 127.0.0.1:81; server 127.0.0.1:82;"}'\'');'
```

**Comment by millken** [comment]
@zmedico ok, i found it.
the problem is **`;`** https://github.com/otoolep/rqlite/blob/master/server/server.go#L503
sql 
````INSERT INTO "server" ("id", "servername", "setting")VALUES(2,"www.test1.com",'{"gzip": 1, "upstream": "server 127.0.0.1:81; server 127.0.0.1:82;"}');'```` 
was split into 
`INSERT INTO "server" ("id", "servername", "setting")VALUES(2,"www.test1.com",'{"gzip": 1, "upstream": "server 127.0.0.1:81`
 and 
`server 127.0.0.1:82;"}');`

**Comment by otoolep** [comment]
OK @millken -- yeah that is an issue. The splitting is quite naive, as you have pointed out. 

This would probably require some more sophisticated parsing of the query string. I can take a look -- PRs welcome too. 

You could try a different delimiter, as a workaround. Or normalize the data with an `upstream` table.

**Comment by otoolep** [comment]
I think probably the best way to fix this is that API should also support a JSON-formatted body for the query. That would make it easy to unambiguously send multiple INSERTS at once.

**Comment by otoolep** [comment]
There is now an effective solution for this in master -- you can specify the multiple INSERTs as the body of the POST request.

Master is still in development, but you should be able to do what you need now. Please let me know if this doesn't work.

**Comment by otoolep** [comment]
Check the README for all the latest details.
