### ISSUE TITLE
Support specifying the SQLite DSN

### ISSUE THREAD

**Issue by millken** [otoolep/rqlite#55]
rqlite should support  query parameter, for example 
````
db, err := sql.Open("sqlite3", "test.db?cache=shared&mode=rwc")
````

**Comment by otoolep** [comment]
Good idea.

The DSNs supported by the `Open` called documented at https://godoc.org/github.com/mattn/go-sqlite3#SQLiteDriver.Open will be supported once https://github.com/otoolep/rqlite/pull/54 merges to master.

**Comment by otoolep** [comment]
Master now supports this, though I have ideas for enhancing it further. You can now pass the "query params" via the `dsn` switch. E.g.

`./rqlited -dsn="cache=shared" data`

Let me know what you think @millken.

**Comment by otoolep** [comment]
I'd like to make this support even more general, so one could specify, say, a memory-only database.

**Comment by otoolep** [comment]
All done for now.
