### ISSUE TITLE
Non-standard use of double quotes around string literals in Readme

### ISSUE THREAD

**Issue by ddevienne** [otoolep/rqlite#59]
Although SQLite does support that notation, it is invalid SQL, and supported only for legacy reasons, and Dr. Richard Hipp has several time expressed regret from this decision.

That syntax further requires escaping the double-quotes in JSON, while single-quote do not need escaping, leading to more readable example.

**Comment by otoolep** [comment]
A bit better now.

https://github.com/otoolep/rqlite/commit/9b202c484a6e8e3c3d508effdb4a3904d4a7bbd8
