### ISSUE TITLE
Report of timings via text and embedded unit (uom), using unicode chars even

### ISSUE THREAD

**Issue by ddevienne** [otoolep/rqlite#60]
Numbers are best represented as numbers in JSON, not text.

And the semantic and unit of that number should be either fixed, for example milliseconds, or the unit of measure should be specified in its own JSON bit.

The current design makes for nicely readable output, but is a poor choice for machine parsable output, since the text value must currently be parsed itself, despite the document returned already having been parsed by JSON.

There could be any number of alternative output, like
```json
{
"time": 0.0123,
"time-sec": 0.0123,
"time": [0.0123, "s"],
"time": [12.3, "ms"],
"time": [0.0123, 1.0],
"time": [12.3, 1e-3],
"time": { "value": 12.3, "uom": "ms"}
}
```

I first simplest is best, and sticking to the second, the SI unit, the first solution is best IMHO.

My $0.02 :)

**Comment by otoolep** [comment]
Agreed @ddevienne -- fair point, and I had been considering it myself.

**Comment by otoolep** [comment]
Fixed by https://github.com/otoolep/rqlite/commit/fac68c3cdd219e18d6c89972c25096a0f6e26d3f
