### ISSUE TITLE
Is GET the right method for bulk queries?

### ISSUE THREAD

**Issue by zmedico** [otoolep/rqlite#61]
This example from README.md fails to work with curl (tested with curl versions 7.45.0 and 7.47.1):
```
$ curl -L -G 'localhost:4001/db?pretty' -H "Content-Type: application/json" -d '[
    "SELECT * FROM foo",
    "SELECT * FROM bar"
]'
curl: (3) Illegal characters found in URL
```
Given that the [HTTP/1.1 spec says the body of a GET request is supposed to be ignored](http://stackoverflow.com/a/983458), I'm not sure that embedding queries in the body was your intention (but I'll go along if you'd like to ignore the spec).

Looking at the Service.handleQuery method, I see that it checks for an empty q= query parameter. However, I have not yet found a curl command both curl and rqlite (current master branch) will successfully respond to, given a JSON body.

I understand that the master branch is under development, and it may be that this is intentional breakage. Anyway, I'd like some clarification on the intended request format, and I'd be happy to send a pull request once the intention is clear to me.

**Comment by otoolep** [comment]
OK, yeah, you're right @zmedico -- I thought that worked.

I am open to the idea of making it a `POST` (though the URL param version would be a `GET`). Let me take a look.

**Comment by otoolep** [comment]
OK, the specific issue with the README has been fixed by this:

https://github.com/otoolep/rqlite/commit/f38eaa16e566a460f4b4babc943a43fa37fc9dac

I need to think more about `GET` vs. `POST`. I am ok with changing it to `POST`, it does seem more standard.

**Comment by otoolep** [comment]
I've changed the API to POST for bulk queries. See the README for details.

Let me know what you think @zmedico

**Comment by zmedico** [comment]
Looks good, thank you!
