### ISSUE TITLE
Race condition initializing db.sqlite3conn variable in the db.Open() function

### ISSUE THREAD

**Issue by zmedico** [otoolep/rqlite#72]
The changes for issue #52 have exposed a race condition for initialization of the db.sqlite3conn variable in the db.Open() function. The result is that the DB instance returned from db.Open() can contain a nil sqlite3conn variable if the relevant ConnectHook did not execute soon enough.

Maybe this only happens on the first run of rqlite, when creating the ~/node.1 directory. I guess the `dbc.Ping()` line is intended to prevent this race, but apparently it's not entirely effective.

Maybe the best solution is to bypass sql.Open, and call SQLiteDriver.Open directly. It's synchronous:
```
d := sqlite3.SQLiteDriver{}
conn, err := d.Open(":memory:")
```

**Comment by otoolep** [comment]
Thanks @zmedico 

If I make that change I need to change a lot of code, since the type returned by that `Open` call is different than what comes back from the current `Open` call.

I agree current code is not great. Let me see if I can fix it up.

**Comment by otoolep** [comment]
Yeah, more I think about this, the more I think I should go straight to the SQLite3 driver. It's not like there are plans for rqlite to support any other type of database.

When I first created rqlite I deliberately used the general Go interface for accessing the SQLite database. There isn't any real need to do so.

**Comment by otoolep** [comment]
This will be fixed by https://github.com/otoolep/rqlite/issues/73

**Comment by otoolep** [comment]
No longer an issue, thanks to #74
