### ISSUE TITLE
rqlited: No such file or directory

### ISSUE THREAD

**Issue by Sooriya10** [otoolep/rqlite#78]
drwxrwxr-x 2 Sooriya Sooriya 4096 Apr 10 01:13 bin
drwxrwxr-x 3 Sooriya Sooriya 4096 Apr 10 01:13 pkg
drwxrwxr-x 3 Sooriya Sooriya 4096 Apr 10 01:13 src

Sooriya@AirP2P:~/rqlite$ $GOPATH/bin/rqlited ~/node.1
-bash: /home/Sooriya/rqlite/bin/rqlited: No such file or directory

Sooriya@AirP2P:~/rqlite$ cd bin

Sooriya@AirP2P:~/rqlite/bin$ ls -la
-rwxrwxr-x 1 Sooriya Sooriya 24000 Apr 10 01:13 rqlite
Sooriya@AirP2P:~/rqlite/bin$

**Comment by otoolep** [comment]
You haven't given me enough context. I need to see your entire build session.

**Comment by otoolep** [comment]
I just checked the build instructions again. It all works fine. Please provide more context if you still can't build the code.

**Comment by otoolep** [comment]
```
~ $ mkdir rqlite # Or any directory of your choice.
~ $ cd rqlite/
~/rqlite $ export GOPATH=$PWD
~/rqlite $ go get -t github.com/otoolep/rqlite/...
~/rqlite $ $GOPATH/bin/rqlited ~/node.1
[rqlited] 2016/04/09 18:37:48 rqlited starting, version 2.1, commit unknown, branch unknown
[store] 2016/04/09 18:37:49 SQLite database opened at /home/philip/node.1/db.sqlite
[store] 2016/04/09 18:37:49 enabling single-node mode
2016/04/09 18:37:49 [INFO] raft: Node at 127.0.0.1:4002 [Follower] entering Follower state
2016/04/09 18:37:50 [WARN] raft: Heartbeat timeout reached, starting election
2016/04/09 18:37:50 [INFO] raft: Node at 127.0.0.1:4002 [Candidate] entering Candidate state
2016/04/09 18:37:50 [DEBUG] raft: Votes needed: 1
2016/04/09 18:37:50 [DEBUG] raft: Vote granted from 127.0.0.1:4002. Tally: 1
2016/04/09 18:37:50 [INFO] raft: Election won. Tally: 1
2016/04/09 18:37:50 [INFO] raft: Node at 127.0.0.1:4002 [Leader] entering Leader state
2016/04/09 18:37:50 [DEBUG] raft: Node 127.0.0.1:4002 updated peer set (2): [127.0.0.1:4002]
2016/04/09 18:37:50 [DEBUG] raft: Node 127.0.0.1:4002 updated peer set (2): [127.0.0.1:4002]
^C[rqlited] 2016/04/09 18:37:51 rqlite server stopped
```

**Comment by Sooriya10** [comment]
Thanks for checking!
Still having issue on my system
----

go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

Sooriya@AirP2P:~$ cd rqlite/Sooriya@AirP2P:~/rqlite$ export GOPATH=$PWDSooriya@AirP2P:~/rqlite$ go get -t github.com/otoolep/rqlite/...# github.com/mattn/go-sqlite3Go type not supported in export: [0]byteGo type not supported in export: [0]byteGo type not supported in export: [0]byteGo type not supported in export: [0]byteGo type not supported in export: [0]byteSooriya@AirP2P:~/rqlite$ go get -t github.com/otoolep/rqlite/.Sooriya@AirP2P:~/rqlite$ go get -t github.com/otoolep/rqlite/..can't load package: package github.com/otoolep: no buildable Go source files in /home/Sooriya/rqlite/src/github.com/otoolepSooriya@AirP2P:~/rqlite$ go get -t github.com/otoolep/rqlite/...# github.com/mattn/go-sqlite3Go type not supported in export: [0]byteGo type not supported in export: [0]byteGo type not supported in export: [0]byteGo type not supported in export: [0]byteGo type not supported in export: [0]byteSooriya@AirP2P:~/rqlite$ ls -ltotal 12drwxrwxr-x 2 Sooriya Sooriya 4096 Apr 10 03:19 bindrwxrwxr-x 3 Sooriya Sooriya 4096 Apr 10 03:19 pkgdrwxrwxr-x 3 Sooriya Sooriya 4096 Apr 10 03:16 srcSooriya@AirP2P:~/rqlite$ cd binSooriya@AirP2P:~/rqlite/bin$ ls -ltotal 24-rwxrwxr-x 1 Sooriya Sooriya 24000 Apr 10 03:19 rqlite

There is no rqlited file?





Date: Sat, 9 Apr 2016 18:40:20 -0700

**Comment by otoolep** [comment]
Something is up with your build of go-sqlite3. This is not a rqlite issue, but the error is blocking rqlited from being built. 

I suggest you visit https://github.com/mattn/go-sqlite3 and see if there is any help there.

**Comment by Sooriya10** [comment]
Thanks!

Date: Sat, 9 Apr 2016 20:40:59 -0700

**Comment by otoolep** [comment]
@Sooriya10 -- what version of Go are you using? You must use at least version 1.4.

**Comment by Sooriya10** [comment]
Sooriya@AirP2P:~/rqlite$ gvm list
gvm gos (installed)   go1.4   go1.5   go1.6

Date: Sat, 9 Apr 2016 21:56:25 -0700

**Comment by otoolep** [comment]
Yeah, OK, I think you need to check with the other repo, I'm not sure what is going on.

**Comment by otoolep** [comment]
See https://github.com/mattn/go-sqlite3/issues/245

**Comment by otoolep** [comment]
Show me the output of `which go`. Just because gvm shows those versions installed, that doesn't mean they are on the path. You must explicitly tell gvm to use them.

**Comment by otoolep** [comment]
```
~ $ which go
/home/philip/.gvm/gos/go1.5/bin/go
~ $ 
```

**Comment by Sooriya10** [comment]
Sooriya@AirP2P:/home/work/src/user$ which go/usr/bin/go

Date: Sat, 9 Apr 2016 23:18:48 -0700

**Comment by otoolep** [comment]
OK, I'm stumped. :-(

**Comment by otoolep** [comment]
Perhaps you can use a pre-built binary, until you sort out the compilation issue. 

https://github.com/otoolep/rqlite/releases

**Comment by Sooriya10** [comment]
Thanks for trying! and quick responses.. I'll give another go at before giving it up 
Date: Sat, 9 Apr 2016 23:29:26 -0700

**Comment by Sooriya10** [comment]
Thanks for this!
2016/04/10 06:35:59 [INFO] raft: Node at 127.0.0.1:4002 [Follower] entering Follower state2016/04/10 06:36:00 [WARN] raft: Heartbeat timeout reached, starting election2016/04/10 06:36:00 [INFO] raft: Node at 127.0.0.1:4002 [Candidate] entering Candidate state2016/04/10 06:36:00 [DEBUG] raft: Votes needed: 12016/04/10 06:36:00 [DEBUG] raft: Vote granted from 127.0.0.1:4002. Tally: 12016/04/10 06:36:00 [INFO] raft: Election won. Tally: 12016/04/10 06:36:00 [INFO] raft: Node at 127.0.0.1:4002 [Leader] entering Leader state2016/04/10 06:36:00 [DEBUG] raft: Node 127.0.0.1:4002 updated peer set (2): [127.0.0.1:4002]
Now I can test it!

Date: Sat, 9 Apr 2016 23:33:53 -0700

**Comment by Sooriya10** [comment]
Thanks, Pre-build work!. Made 5 nodes, Ithink thats what we want for our app
/execute?pretty&timings' -H "Content-Type: application/json" -d "[>     \"INSERT INTO foo(name) VALUES('fiona')\",>     \"INSERT INTO foo(name) VALUES('sinead')\"> ]"{    "results": [        {            "last_insert_id": 2,            "rows_affected": 1,            "time": 0.2434453        },        {            "last_insert_id": 3,            "rows_affected": 1,            "time": 0.46698310000000004        }    ],    "time": 0.9060072}Sooriya@AirP2P:~/rqlite/rqlited-v2.1-linux-amd64$ sqlite3 ~/node.5/db.sqliteSQLite version 3.12.0 2016-03-29 10:14:15Enter ".help" for usage hints.sqlite> select * from foo;1|fiona2|fiona3|sineadsqlite>





Date: Sat, 9 Apr 2016 23:33:53 -0700
