### ISSUE TITLE
rqlite isn't work in Windows.

### ISSUE THREAD

**Issue by ejzhang** [otoolep/rqlite#80]
I builded rqlite in windows, but only display "I am the rqlite CLI!" when run it with any parameters.
> c:\rqlite\bin>rqlite.exe
I am the rqlite CLI!

> c:\rqlite\bin>rqlite.exe -h
I am the rqlite CLI!

> c:\rqlite\bin>rqlite.exe --h
I am the rqlite CLI!

> c:\rqlite\bin>rqlite.exe -help
I am the rqlite CLI!

> c:\rqlite\bin>rqlite.exe --help
I am the rqlite CLI!

> c:\rqlite\bin>rqlite.exe -?
I am the rqlite CLI!

> c:\rqlite\bin>rqlite.exe --?
I am the rqlite CLI!

**Comment by ejzhang** [comment]
There are some redeclared warning when i build it.
> c:\rqlite>go get -t github.com/otoolep/rqlite/...
 # compress/flate
C:\Program Files\Go\src\compress\flate\inflate.go:30: fixedHuffmanDecoder redeclared in this block
        previous declaration at C:\Program Files\Go\src\compress\flate\fixedhuff.go:78
 # hash/crc32
C:\Program Files\Go\src\hash\crc32\crc32_amd64x.go:14: haveSSE42 redeclared in this block
        previous declaration at C:\Program Files\Go\src\hash\crc32\crc32_amd64.go:13
C:\Program Files\Go\src\hash\crc32\crc32_amd64x.go:18: castagnoliSSE42 redeclared in this block
        previous declaration at C:\Program Files\Go\src\hash\crc32\crc32_amd64.go:19
C:\Program Files\Go\src\hash\crc32\crc32_amd64x.go:20: sse42 redeclared in this block
        previous declaration at C:\Program Files\Go\src\hash\crc32\crc32_amd64.go:26
C:\Program Files\Go\src\hash\crc32\crc32_amd64x.go:22: updateCastagnoli redeclared in this block
        previous declaration at C:\Program Files\Go\src\hash\crc32\crc32_amd64.go:29

**Comment by otoolep** [comment]
You must run rqlited, not rqlite. I also do not have access to a Windows machine so can't help you there. I am open to changes to make it work on Windows though. 

----------------------------------
http://www.philipotoole.com

**Comment by ejzhang** [comment]
But how to build rqlited.exe? There's rqlite.exe only in the bin folder.

**Comment by otoolep** [comment]
As explained in the README, please consult this:

https://github.com/otoolep/rqlite/blob/master/CONTRIBUTING.md
