### ISSUE TITLE
Insert a record to a none master node, it will crash

### ISSUE THREAD

**Issue by Sooriya10** [otoolep/rqlite#81]
>sqlite3 ~/node.3/db.sqlite
INSERT INTO foo(name) VALUES('Crashed the system')

**Comment by otoolep** [comment]
I don't understand this bug. Can you please provide more details? I can't reproduce this issue, since you have not provided enough information.

Just to be clear, writing to the SQLite file underneath an rqlite node is *not* supported.

**Comment by Sooriya10** [comment]
I'll test it again and get a report later.
BTW: Can this "writing to the SQLite file underneath an rqlite node" be controlled, because someone might hack/accidentally  do this.
Otherwise that will be a problem for the application we are rethinking of. It needs replication, but the replicate set should not be able to fiddle with and must be "READ" only max.
Date: Sun, 10 Apr 2016 21:06:49 -0700

**Comment by otoolep** [comment]
>BTW: Can this "writing to the SQLite file underneath an rqlite node" be controlled, because someone might hack/accidentally do this.

I am open to suggestions. But if you need a dump of the SQLite database, use the backup endpoint. Don't access the file directly.

**Comment by Sooriya10** [comment]
Thanks for asking suggestion. I'm sure your replica set for sqlite3 solution is ideal for many situations/applications.
For us, would that be possible to configure the other Nodes that they never will be able Insert/Update or Delete. i.e. those operation only via the master database and only replicate to the other nodes...

**Comment by otoolep** [comment]
> For us, would that be possible to configure the other Nodes that they never will be able Insert/Update or Delete. i.e. those operation only via the master database and only replicate to the other nodes...

The answer to your requirement is to only go through the HTTP API on the leader, and don't write to the SQLite file directly. I can't prevent you from doing this, so you shouldn't do it, as rqlite doesn't support this kind of operation.

I'm closing this bug since it sounds like you're writing to the SQLite file directly and you're not supposed to do that. Let know if this is not what you're doing.

**Comment by Sooriya10** [comment]
Yes, I was writing directly a followers node to test it.  Your solution should "not" allow  that.  It is useless for us if it allows to do that.
Your solution is vulnerable for hacking, and accidental writing to the followers.  Hence they not fall in this basic rule " ensuring that each node in the cluster agrees upon the same series of state transitions"
Sorry to say this, because allowing this back door entries via the followers, I believe your Rqlite is not a RAFT implementation.
Date: Mon, 11 Apr 2016 04:39:39 -0700

**Comment by otoolep** [comment]
>Yes, I was writing directly a followers node to test it.  Your solution should "not" allow  that.  It is useless for us if it allows to do that.

You can't write to anything but the leader. The system explicitly prevents this is use the API. You can't write to a follower -- the request will be rejected. 

And If you are writing to the SQLite underneath a node, that is wrong. I've explicitly explained that the system does not support that.

>Your solution is vulnerable for hacking, and accidental writing to the followers.  Hence they not fall in this basic rule " ensuring that each node in the cluster agrees upon the same series of state transitions"

rqlite does not enforce security at the HTTP API level. Use, say, nginx in front of the rqlite API to do this, or roll your own proxy. Or use an API Gateway.

And if you're worried about people writing to the file on disk underneath a node, then don't allow people access to the file system. 

>Sorry to say this, because allowing this back door entries via the followers, I believe your Rqlite is not a RAFT implementation.

I don't mean to be rude, but you don't appear to understand what rqlite is about.

**Comment by Sooriya10** [comment]
Sorry Peter, Im a DBA with 15+ years of experience. What is the point having a database solution open for hacking, specially on SQLlie3 which are implemented on the client devices (or distributed systems ). So the users hack into it (or anyone have access to the device)
I think you should check with someone with the RAFT protocol expertise that yours is a RAFT implementation if the followers also allowed the CRUD operation on them..
Please warn the users of your solution, The databases may go out of sync..
BTW: I believe you may be able add further security control to your implementation and make it fully RAFT implementation.  if you would like to discuss a solution let me know.

Date: Mon, 11 Apr 2016 15:18:02 -0700

**Comment by otoolep** [comment]
Sorry @Sooriya10 -- you simply don't understand what you're talking about.

**Comment by Sooriya10** [comment]
Scenario,
With your "current" solution.
Master and 3 followers nodes have the records Id,Name, Account Balance"1, 'John', $3502, 'Shane',$1003,'Malcolm',$500
and the follower node 5 suddenly have records being hacked (or accidentally changed) to
Id,Name, Account Balance"1, 'John', $3502, 'Shane', $1003,'Julia',$500  (record updated to different person)4,''Con',$5000000 (record has been added)
And we have implemented a banking solution and given to the operational team.
Who is responsible for this?
Date: Mon, 11 Apr 2016 15:50:21 -0700

**Comment by otoolep** [comment]
>Who is responsible for this?

The incompetent people running your systems, that's who.

**Comment by zmedico** [comment]
@Sooriya10: It sounds like maybe you're looking for something like blockchain, which is much different from RAFT.

**Comment by Sooriya10** [comment]
Thanks for the tip.. hope Rqlite is useful for many other apps..
Thanks Peter for you tolerance and quick responses.
Date: Mon, 11 Apr 2016 16:04:44 -0700

**Comment by Sooriya10** [comment]
Thanks Zac, If you happened to know any blockchain implementation on SQLite3 or any other database. Please let me know.!

**Comment by Sooriya10** [comment]
@Peter,

I think your solution could have another couple of implementation options. hence 3 flavors!!!

1) Check out of sync follower databases, re-sync them based on the majority- after all this is a consensus system, so this should work perfectly. Also send alerts if this happen

2) Implement a file level security. i.e all the followers data base are read only to start with. if the follower become master than also change the file permission.

**Comment by otoolep** [comment]
All that is way beyond the scope of rqlite.

**Comment by Sooriya10** [comment]
Sorry Peter, I was expecting it was to be like block-chain.
BTW: But I'm still testing your rqlite as it is and see it is useful for us someway

Date: Mon, 11 Apr 2016 23:27:13 -0700

**Comment by zmedico** [comment]
> Thanks Zac, If you happened to know any blockchain implementation on SQLite3 or any other database. Please let me know.!

I think what you want is rqlite with support for using [public-key cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography) to sign all transactions. Each transaction must be signed with a private key that is not divulged to the read-only nodes. The read-only nodes can use the corresponding public key to verify the integrity of transactions, but they won't be able to create new transactions unless they have access to the private key.

In order to support something like this, you're probably need it to be built into the [RAFT library](https://github.com/hashicorp/raft).

> All that is way beyond the scope of rqlite.

Indeed, file level security is way out of scope, since it's a system administration issue. The cryptographic security is out of scope due to it being the domain of the [RAFT library](https://github.com/hashicorp/raft).

**Comment by Sooriya10** [comment]
Thanks for both of you!! clarifying the technology capabilities and the solution..

Date: Tue, 12 Apr 2016 00:29:37 -0700
