### ISSUE TITLE
Support HTTPS API

### ISSUE THREAD

**Issue by otoolep** [otoolep/rqlite#82]
rqlite should support HTTPS connections. This will require allowing the user to supply a cert and private key.

**Comment by zmedico** [comment]
I've found an example for mutual authentication using tls.Config{ClientAuth: tls.RequireAndVerifyClientCert}:

http://www.bite-code.com/2015/06/25/tls-mutual-auth-in-golang/

**Comment by otoolep** [comment]
Fixed by #84
